// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Optsol.Playground.Infra.Data.Context;

namespace Optsol.Playground.Infra.Migrations
{
    [DbContext(typeof(PlaygroundContext))]
    [Migration("20210623213845_ExemploHeranca")]
    partial class ExemploHeranca
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Optsol.Playground.Domain.Entities.CartaoCreditoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoVerificacao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Validade")
                        .HasMaxLength(200)
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("CartaoCredito");
                });

            modelBuilder.Entity("Optsol.Playground.Domain.Entities.ClienteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ClienteId");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedDate");

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Optsol.Playground.Domain.Entities.ClientePessoaFisicaEntity", b =>
                {
                    b.HasBaseType("Optsol.Playground.Domain.Entities.ClienteEntity");

                    b.Property<string>("Documento")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ClientePessoaFisica");
                });

            modelBuilder.Entity("Optsol.Playground.Domain.Entities.ClientePessoaJuridicaEntity", b =>
                {
                    b.HasBaseType("Optsol.Playground.Domain.Entities.ClienteEntity");

                    b.Property<string>("NumeroCnpj")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ClientePessoaJuridica");
                });

            modelBuilder.Entity("Optsol.Playground.Domain.Entities.CartaoCreditoEntity", b =>
                {
                    b.HasOne("Optsol.Playground.Domain.Entities.ClienteEntity", "Cliente")
                        .WithMany("Cartoes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Optsol.Playground.Domain.Entities.ClienteEntity", b =>
                {
                    b.OwnsOne("Optsol.Playground.Domain.ValueObjects.EmailValueObject", "Email", b1 =>
                        {
                            b1.Property<Guid>("ClienteEntityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Email");

                            b1.HasKey("ClienteEntityId");

                            b1.ToTable("Cliente");

                            b1.WithOwner()
                                .HasForeignKey("ClienteEntityId");
                        });

                    b.OwnsOne("Optsol.Playground.Domain.ValueObjects.NomeValueObject", "Nome", b1 =>
                        {
                            b1.Property<Guid>("ClienteEntityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Nome");

                            b1.Property<string>("SobreNome")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Sobrenome");

                            b1.HasKey("ClienteEntityId");

                            b1.ToTable("Cliente");

                            b1.WithOwner()
                                .HasForeignKey("ClienteEntityId");
                        });

                    b.Navigation("Email");

                    b.Navigation("Nome");
                });

            modelBuilder.Entity("Optsol.Playground.Domain.Entities.ClientePessoaFisicaEntity", b =>
                {
                    b.HasOne("Optsol.Playground.Domain.Entities.ClienteEntity", null)
                        .WithOne()
                        .HasForeignKey("Optsol.Playground.Domain.Entities.ClientePessoaFisicaEntity", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Optsol.Playground.Domain.Entities.ClientePessoaJuridicaEntity", b =>
                {
                    b.HasOne("Optsol.Playground.Domain.Entities.ClienteEntity", null)
                        .WithOne()
                        .HasForeignKey("Optsol.Playground.Domain.Entities.ClientePessoaJuridicaEntity", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Optsol.Playground.Domain.Entities.ClienteEntity", b =>
                {
                    b.Navigation("Cartoes");
                });
#pragma warning restore 612, 618
        }
    }
}
